In [103]:
import numpy as np
import pandas as pd

In [104]:
dataset = pd.read_csv('adult.csv')
dataset.head()
dataset.head()

39          State-gov   77516   Bachelors   13        Never-married  \
0  50   Self-emp-not-inc   83311   Bachelors   13   Married-civ-spouse   
1  38            Private  215646     HS-grad    9             Divorced   
2  53            Private  234721        11th    7   Married-civ-spouse   
3  28            Private  338409   Bachelors   13   Married-civ-spouse   
4  37            Private  284582     Masters   14   Married-civ-spouse   

         Adm-clerical   Not-in-family   White     Male   2174   0   40  \
0     Exec-managerial         Husband   White     Male      0   0   13   
1   Handlers-cleaners   Not-in-family   White     Male      0   0   40   
2   Handlers-cleaners         Husband   Black     Male      0   0   40   
3      Prof-specialty            Wife   Black   Female      0   0   40   
4     Exec-managerial            Wife   White   Female      0   0   40   

    United-States   <=50K  
0   United-States   <=50K  
1   United-States   <=50K  
2   United-States   <=50K  
3            Cuba   <=50K  
4   United-States   <=50K

In [105]:
colnames= ['Age', 'Workclass', 'Fnlwgt', 'Education','education_num','marital_status','occupation','relationship','race','sex','capital_gain','capital_loss','hours_per_week','native_country','income']
dataset = pd.read_csv('adult.csv',names=colnames, header=None)
dataset.head()

Age          Workclass  Fnlwgt   Education  education_num  \
0   39          State-gov   77516   Bachelors             13   
1   50   Self-emp-not-inc   83311   Bachelors             13   
2   38            Private  215646     HS-grad              9   
3   53            Private  234721        11th              7   
4   28            Private  338409   Bachelors             13   

        marital_status          occupation    relationship    race      sex  \
0        Never-married        Adm-clerical   Not-in-family   White     Male   
1   Married-civ-spouse     Exec-managerial         Husband   White     Male   
2             Divorced   Handlers-cleaners   Not-in-family   White     Male   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female   

   capital_gain  capital_loss  hours_per_week  native_country  income  
0          2174             0              40   United-States   <=50K  
1             0             0              13   United-States   <=50K  
2             0             0              40   United-States   <=50K  
3             0             0              40   United-States   <=50K  
4             0             0              40            Cuba   <=50K

In [106]:
print("Original features:\n", list(dataset.columns), "\n")
data_dummies = pd.get_dummies(dataset)
print("Features after get_dummies:\n", list(data_dummies.columns))
data_dummies.head()

Original features:
 ['Age', 'Workclass', 'Fnlwgt', 'Education', 'education_num', 'marital_status', 'occupation', 'relationship', 'race', 'sex', 'capital_gain', 'capital_loss', 'hours_per_week', 'native_country', 'income'] 

Features after get_dummies:
 ['Age', 'Fnlwgt', 'education_num', 'capital_gain', 'capital_loss', 'hours_per_week', 'Workclass_ ?', 'Workclass_ Federal-gov', 'Workclass_ Local-gov', 'Workclass_ Never-worked', 'Workclass_ Private', 'Workclass_ Self-emp-inc', 'Workclass_ Self-emp-not-inc', 'Workclass_ State-gov', 'Workclass_ Without-pay', 'Education_ 10th', 'Education_ 11th', 'Education_ 12th', 'Education_ 1st-4th', 'Education_ 5th-6th', 'Education_ 7th-8th', 'Education_ 9th', 'Education_ Assoc-acdm', 'Education_ Assoc-voc', 'Education_ Bachelors', 'Education_ Doctorate', 'Education_ HS-grad', 'Education_ Masters', 'Education_ Preschool', 'Education_ Prof-school', 'Education_ Some-college', 'marital_status_ Divorced', 'marital_status_ Married-AF-spouse', 'marital_status

Age  Fnlwgt  education_num  capital_gain  capital_loss  hours_per_week  \
0   39   77516             13          2174             0              40   
1   50   83311             13             0             0              13   
2   38  215646              9             0             0              40   
3   53  234721              7             0             0              40   
4   28  338409             13             0             0              40   

   Workclass_ ?  Workclass_ Federal-gov  Workclass_ Local-gov  \
0             0                       0                     0   
1             0                       0                     0   
2             0                       0                     0   
3             0                       0                     0   
4             0                       0                     0   

   Workclass_ Never-worked  ...  native_country_ Scotland  \
0                        0  ...                         0   
1                        0  ...                         0   
2                        0  ...                         0   
3                        0  ...                         0   
4                        0  ...                         0   

   native_country_ South  native_country_ Taiwan  native_country_ Thailand  \
0                      0                       0                         0   
1                      0                       0                         0   
2                      0                       0                         0   
3                      0                       0                         0   
4                      0                       0                         0   

   native_country_ Trinadad&Tobago  native_country_ United-States  \
0                                0                              1   
1                                0                              1   
2                                0                              1   
3                                0                              1   
4                                0                              0   

   native_country_ Vietnam  native_country_ Yugoslavia  income_ <=50K  \
0                        0                           0              1   
1                        0                           0              1   
2                        0                           0              1   
3                        0                           0              1   
4                        0                           0              1   

   income_ >50K  
0             0  
1             0  
2             0  
3             0  
4             0  

[5 rows x 110 columns]

In [107]:
dataset.info('income')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   Age             32561 non-null  int64 
 1   Workclass       32561 non-null  object
 2   Fnlwgt          32561 non-null  int64 
 3   Education       32561 non-null  object
 4   education_num   32561 non-null  int64 
 5   marital_status  32561 non-null  object
 6   occupation      32561 non-null  object
 7   relationship    32561 non-null  object
 8   race            32561 non-null  object
 9   sex             32561 non-null  object
 10  capital_gain    32561 non-null  int64 
 11  capital_loss    32561 non-null  int64 
 12  hours_per_week  32561 non-null  int64 
 13  native_country  32561 non-null  object
 14  income          32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB


In [108]:
X = data_dummies.iloc[:, :-2].values
y = data_dummies.iloc[:, -1].values
data_dummies.head()

Age  Fnlwgt  education_num  capital_gain  capital_loss  hours_per_week  \
0   39   77516             13          2174             0              40   
1   50   83311             13             0             0              13   
2   38  215646              9             0             0              40   
3   53  234721              7             0             0              40   
4   28  338409             13             0             0              40   

   Workclass_ ?  Workclass_ Federal-gov  Workclass_ Local-gov  \
0             0                       0                     0   
1             0                       0                     0   
2             0                       0                     0   
3             0                       0                     0   
4             0                       0                     0   

   Workclass_ Never-worked  ...  native_country_ Scotland  \
0                        0  ...                         0   
1                        0  ...                         0   
2                        0  ...                         0   
3                        0  ...                         0   
4                        0  ...                         0   

   native_country_ South  native_country_ Taiwan  native_country_ Thailand  \
0                      0                       0                         0   
1                      0                       0                         0   
2                      0                       0                         0   
3                      0                       0                         0   
4                      0                       0                         0   

   native_country_ Trinadad&Tobago  native_country_ United-States  \
0                                0                              1   
1                                0                              1   
2                                0                              1   
3                                0                              1   
4                                0                              0   

   native_country_ Vietnam  native_country_ Yugoslavia  income_ <=50K  \
0                        0                           0              1   
1                        0                           0              1   
2                        0                           0              1   
3                        0                           0              1   
4                        0                           0              1   

   income_ >50K  
0             0  
1             0  
2             0  
3             0  
4             0  

[5 rows x 110 columns]

In [109]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [110]:
print(y_train)

[0 0 1 ... 0 1 0]


In [111]:
print(y_train)

[0 0 1 ... 0 1 0]


In [112]:
print(X_test)

[[    27 177119     10 ...      1      0      0]
 [    27 216481     13 ...      1      0      0]
 [    25 256263     12 ...      1      0      0]
 ...
 [    38 229236      9 ...      0      0      0]
 [    63 213095     13 ...      1      0      0]
 [    47 186009     10 ...      0      0      0]]


In [113]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [114]:
print(X_train)

[[ 1.49894077 -1.2079589  -0.80338299 ...  0.33936755 -0.04296689
  -0.02307887]
 [ 2.38045121 -0.08366135  1.53114709 ...  0.33936755 -0.04296689
  -0.02307887]
 [ 0.2501343  -0.77396423  1.53114709 ...  0.33936755 -0.04296689
  -0.02307887]
 ...
 [-1.14559057 -1.36469155 -0.0252063  ...  0.33936755 -0.04296689
  -0.02307887]
 [ 0.47051192  0.24865765  2.30932378 ...  0.33936755 -0.04296689
  -0.02307887]
 [-0.99867216 -0.02508527 -0.0252063  ...  0.33936755 -0.04296689
  -0.02307887]]


In [115]:
print(X_test)

[[-0.85175375 -0.11784965 -0.0252063  ...  0.33936755 -0.04296689
  -0.02307887]
 [-0.85175375  0.25451337  1.14205874 ...  0.33936755 -0.04296689
  -0.02307887]
 [-0.99867216  0.63084957  0.7529704  ...  0.33936755 -0.04296689
  -0.02307887]
 ...
 [-0.04370251  0.37517518 -0.41429464 ... -2.94665767 -0.04296689
  -0.02307887]
 [ 1.79277758  0.22248194  1.14205874 ...  0.33936755 -0.04296689
  -0.02307887]
 [ 0.61743032 -0.03375059 -0.0252063  ... -2.94665767 -0.04296689
  -0.02307887]]


# Decision Tree


In [116]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [117]:
print(classifier.predict(sc.transform(X_train)))

[0 0 0 ... 0 0 0]


In [118]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [1 1]
 [0 0]]


In [119]:
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report
cm = confusion_matrix(y_test, y_pred)
print(cm)
DT_accu=accuracy_score(y_test, y_pred)
print(classification_report(y_test, y_pred))

[[5412  747]
 [ 756 1226]]
              precision    recall  f1-score   support

           0       0.88      0.88      0.88      6159
           1       0.62      0.62      0.62      1982

    accuracy                           0.82      8141
   macro avg       0.75      0.75      0.75      8141
weighted avg       0.82      0.82      0.82      8141




# Random Forest Classifier

In [120]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

In [121]:
print(classifier.predict(sc.transform(X_train)))

[0 0 0 ... 0 0 0]


In [122]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [1 1]
 [0 0]]


In [123]:
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report
cm = confusion_matrix(y_test, y_pred)
print(cm)
RF_accu=accuracy_score(y_test, y_pred)
print(classification_report(y_test, y_pred))

[[5741  418]
 [ 852 1130]]
              precision    recall  f1-score   support

           0       0.87      0.93      0.90      6159
           1       0.73      0.57      0.64      1982

    accuracy                           0.84      8141
   macro avg       0.80      0.75      0.77      8141
weighted avg       0.84      0.84      0.84      8141



# Logistic Regression


In [124]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

LogisticRegression(random_state=0)

In [125]:
print(classifier.predict(sc.transform(X_train)))

[0 0 1 ... 0 1 0]


In [126]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [1 1]
 [0 0]]


In [127]:
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report
cm = confusion_matrix(y_test, y_pred)
print(cm)
LR_accu=accuracy_score(y_test, y_pred)
print(classification_report(y_test, y_pred))

[[5719  440]
 [ 779 1203]]
              precision    recall  f1-score   support

           0       0.88      0.93      0.90      6159
           1       0.73      0.61      0.66      1982

    accuracy                           0.85      8141
   macro avg       0.81      0.77      0.78      8141
weighted avg       0.84      0.85      0.85      8141



# KNN CLASSIFIER

In [128]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

KNeighborsClassifier()

In [129]:
print(classifier.predict(sc.transform(X_train)))

[0 0 0 ... 0 1 0]


In [130]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [1 0]
 ...
 [0 0]
 [1 1]
 [0 0]]


In [131]:
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report
cm = confusion_matrix(y_test, y_pred)
print(cm)
KNN_accu = accuracy_score(y_test, y_pred)
print(classification_report(y_test, y_pred))

[[5562  597]
 [ 854 1128]]
              precision    recall  f1-score   support

           0       0.87      0.90      0.88      6159
           1       0.65      0.57      0.61      1982

    accuracy                           0.82      8141
   macro avg       0.76      0.74      0.75      8141
weighted avg       0.82      0.82      0.82      8141



# SVC Classifier (with linear kernel)

In [132]:
# Importing SVM from sklearn
from sklearn import svm

In [133]:
# Creating the SVM model and training the model with X_train and y_train
SVM_m = svm.SVC()
SVM_m.fit(X_train, y_train)

SVC()

In [134]:
# Using the X_test to predict the values
y_pred_SVM = SVM_m.predict(X_test)

In [135]:
# Calculating the Confusion Matrix and Accuracy_Score of the model
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
cm = confusion_matrix(y_test, y_pred_SVM)
print("Confusion Matrix = ", cm)
print("*"*80)
# Classification Report
print(classification_report(y_test, y_pred_SVM))
print("*"*80)
SVM_accu = accuracy_score(y_test, y_pred_SVM)
print("SVM Classifier Accuracy = ", SVM_accu)

Confusion Matrix =  [[5789  370]
 [ 867 1115]]
********************************************************************************
              precision    recall  f1-score   support

           0       0.87      0.94      0.90      6159
           1       0.75      0.56      0.64      1982

    accuracy                           0.85      8141
   macro avg       0.81      0.75      0.77      8141
weighted avg       0.84      0.85      0.84      8141

********************************************************************************
SVM Classifier Accuracy =  0.8480530647340622


In [136]:
print("Decision Tree Classifier Accuracy = ", DT_accu)
print("Random Forest Classifier Accuracy = ", RF_accu)
print("KNN Classifier Accuracy = ", KNN_accu)
print("Logistic Regression Accuracy = ", LR_accu)
print("SVM Classifier Accuracy = ", SVM_accu)

Decision Tree Classifier Accuracy =  0.8153789460754207
Random Forest Classifier Accuracy =  0.8439995086598698
KNN Classifier Accuracy =  0.8217663677680874
Logistic Regression Accuracy =  0.8502640953199853
SVM Classifier Accuracy =  0.8480530647340622



Logistic Regression has the best accuracy